version: '3'
services:
  challenge:
    build: challenge/.
    image: crossbeam/challenge
    tty: true
    ports:
      - 8080:8080
    volumes:
      - ../app/crossbeam:/app
    entrypoint: /bin/bash -c "cd /app/challenge && mix deps.get && mix run --no-halt"
    # escript.build && ./challenge $${0} $${1}"

    